# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\nsfm_server\"t\n\x0b\x44\x61taRequest\x12\x0f\n\x07type_id\x18\x01 \x01(\x05\x12\x12\n\x05image\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x12+\n\x06\x63\x61mera\x18\x03 \x01(\x0b\x32\x16.sfm_server.DataCameraH\x01\x88\x01\x01\x42\x08\n\x06_imageB\t\n\x07_camera\":\n\nDataCamera\x12\x0b\n\x03mrt\x18\x01 \x01(\x02\x12\t\n\x01k\x18\x02 \x03(\x02\x12\t\n\x01x\x18\x03 \x01(\x02\x12\t\n\x01y\x18\x04 \x01(\x02\",\n\tDataPoint\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\",\n\tDataColor\x12\t\n\x01r\x18\x01 \x01(\r\x12\t\n\x01g\x18\x02 \x01(\r\x12\t\n\x01\x62\x18\x03 \x01(\r\"V\n\x08\x44\x61taIter\x12$\n\x05point\x18\x01 \x01(\x0b\x32\x15.sfm_server.DataPoint\x12$\n\x05\x63olor\x18\x02 \x01(\x0b\x32\x15.sfm_server.DataColor\".\n\tDataReply\x12!\n\x03row\x18\x01 \x01(\x0b\x32\x14.sfm_server.DataIter2L\n\tSfmServer\x12?\n\x07rebuild\x12\x17.sfm_server.DataRequest\x1a\x15.sfm_server.DataReply\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DATAREQUEST']._serialized_start=28
  _globals['_DATAREQUEST']._serialized_end=144
  _globals['_DATACAMERA']._serialized_start=146
  _globals['_DATACAMERA']._serialized_end=204
  _globals['_DATAPOINT']._serialized_start=206
  _globals['_DATAPOINT']._serialized_end=250
  _globals['_DATACOLOR']._serialized_start=252
  _globals['_DATACOLOR']._serialized_end=296
  _globals['_DATAITER']._serialized_start=298
  _globals['_DATAITER']._serialized_end=384
  _globals['_DATAREPLY']._serialized_start=386
  _globals['_DATAREPLY']._serialized_end=432
  _globals['_SFMSERVER']._serialized_start=434
  _globals['_SFMSERVER']._serialized_end=510
# @@protoc_insertion_point(module_scope)
